#!/bin/sh

USER="qdb"
GROUP="$USER"

# Allow errors to make sure the package can always be removed
set +e

if [ "$1" = "purge" ]; then
    rm -rf /etc/qdb/qdbd.conf
    rmdir --ignore-fail-on-non-empty /etc/qdb/
    rm -rf /var/lib/qdb
    rm -rf /var/run/qdb
    rm -rf /var/log/qdb
    userdel $USER
fi

if [ "$1" != "upgrade" ]; then
    rm -f /etc/systemd/system/qdbd.service
    rm -f /etc/init/qdbd.conf

    if ps -p1 | grep -q systemd; then
        systemctl daemon-reload
    else
        initctl reload-configuration
    fi
fi
