#!/bin/sh

USER="qdb"
GROUP="$USER"
ETC_PATH=/etc/qdb

# Allow errors to make sure the package can always be removed
set +e

if [ "$1" = "purge" ]; then
    rm -f $ETC_PATH/qdbd.conf
    rm -f $ETC_PATH/users.conf
    rm -f $ETC_PATH/cluster_private.key
    rm -f $ETC_PATH/qdbsh_private.key
    rmdir --ignore-fail-on-non-empty $ETC_PATH
    rm -rf /var/lib/qdb
    rm -rf /var/run/qdb
    rm -rf /var/log/qdb
    userdel $USER
fi

if [ "$1" = "remove" ]; then
    rm -f $ETC_PATH/qdbd.conf
    rm -f $ETC_PATH/users.conf
    rm -f $ETC_PATH/cluster_private.key
    rm -f $ETC_PATH/qdbsh_private.key
    rmdir --ignore-fail-on-non-empty $ETC_PATH
    rm -rf /var/run/qdb
    rm -rf /var/log/qdb
    userdel $USER
fi

if [ "$1" != "upgrade" ]; then
    rm -f /etc/systemd/system/qdbd.service
    rm -f /etc/init/qdbd.conf

    if ps -p1 | grep -q systemd; then
        systemctl daemon-reload
    else
        initctl reload-configuration
    fi
fi
