#!/bin/sh

set -eu

USER="qdb"
GROUP="$USER"
ETC_PATH=/etc/qdb
DB_PATH=/var/db/qdb
LOG_PATH=/var/log/qdb

# Database
mkdir -p $DB_PATH
chown $USER:$GROUP $DB_PATH

# Log
mkdir -p $LOG_PATH
touch $LOG_PATH/qdbd.log
chown -R $USER:$GROUP $LOG_PATH

# Config
mkdir -p $ETC_PATH
[ -e $ETC_PATH/qdbd.conf ] || qdbd --gen-config=$ETC_PATH/qdbd.conf --daemonize --log-file=$LOG_PATH/qdbd.log --log-dump=$LOG_PATH/qdbd_error_dump.txt --root=$DB_PATH

sysctl -e -q -p /etc/sysctl.d/30-quasardb.conf

chown root:root /usr/share/qdb/upstart/qdbd.conf

if ps -p1 | grep -q systemd; then
    ln -sf /usr/share/qdb/systemd/qdbd.service /etc/systemd/system/qdbd.service
    systemctl daemon-reload
else
    ln -sf /usr/share/qdb/upstart/qdbd.conf /etc/init/qdbd.conf
    initctl reload-configuration
fi
