#!/bin/sh

USER="qdb"
GROUP="$USER"
ETC_PATH=/etc/qdb

#DEBHELPER#

# Allow errors to make sure the package can always be removed
set +e

if [ "$1" = "purge" ]; then
    rm -f $ETC_PATH/qdbd.conf
    rm -f $ETC_PATH/users.conf
    rm -f $ETC_PATH/cluster_private.key
    rm -f $ETC_PATH/qdbsh_private.key
    rmdir --ignore-fail-on-non-empty $ETC_PATH
    rm -rf /var/lib/qdb
    rm -rf /var/run/qdb
    rm -rf /var/log/qdb
    userdel $USER
fi

if [ "$1" = "remove" ]; then
    rm -f $ETC_PATH/qdbd.conf
    rm -f $ETC_PATH/users.conf
    rm -f $ETC_PATH/cluster_private.key
    rm -f $ETC_PATH/qdbsh_private.key
    rmdir --ignore-fail-on-non-empty $ETC_PATH
    rm -rf /var/run/qdb
    rm -rf /var/log/qdb
    userdel $USER
fi

if [ "$1" = "upgrade" ]
then
    systemctl daemon-reload
    systemctl restart qdbd
else
    systemctl stop qdbd
    systemctl disable qdbd
    rm -f /usr/lib/systemd/system/qdbd.service || true

    systemctl daemon-reload


fi
