#!/bin/sh

set -eu

USER="qdb"
GROUP="$USER"

mkdir -p /etc/qdb

mkdir -p /var/lib/qdb/db
mkdir -p /var/log/qdb
mkdir -p /var/run/qdb

chown $USER:$GROUP /var/lib/qdb/db
chown $USER:$GROUP /var/log/qdb
chown $USER:$GROUP /var/run/qdb

/usr/bin/qdb_generate_config /etc/qdb/ /var/log/qdb /var/lib/qdb/db /usr/share/qdb/console

chown root:root /etc/init/qdbd.conf
chown root:root /etc/init/qdb_httpd.conf

initctl reload-configuration
