#!/bin/sh

# Allow errors to make sure the package can always be removed
set +e

if ps -p1 | grep -q systemd; then

    if systemctl is-active -q qdbd ; then
        echo "Stopping qdbd..."
        systemctl stop qdbd.service
    fi

else

    if initctl status qdbd | grep -q running; then
        echo "Stopping qdbd..."
        initctl --quiet stop qdbd
    fi

fi