#!/bin/sh

set -eu

USER="qdb_http"
GROUP="$USER"
ETC_PATH=/etc/qdb
LOG_PATH=/var/log/qdb_http
WWW_PATH=/usr/share/qdb/www

# Log
mkdir $LOG_PATH
chown $USER:$GROUP $LOG_PATH

# Config
mkdir -p /etc/qdb
[ -e $ETC_PATH/qdb_httpd.conf ] || qdb_httpd --gen-conf=$ETC_PATH/qdb_httpd.conf --daemonize --log-file=$LOG_PATH/qdb_httpd.log --log-dump=$LOG_PATH/qdb_httpd_error_dump.txt --root=$WWW_PATH

chown root:root /usr/share/qdb/upstart/qdb_httpd.conf

if ps -p1 | grep -q systemd; then
    ln -sf /usr/share/qdb/systemd/qdb_httpd.service /etc/systemd/system/qdb_httpd.service
    systemctl daemon-reload
else
    ln -sf /usr/share/qdb/upstart/qdb_httpd.conf /etc/init/qdb_httpd.conf
    initctl reload-configuration
fi
