#!/bin/sh

USER="qdb_http"
GROUP="$USER"
ETC_PATH=/etc/qdb
LOG_PATH=/var/log/qdb_http
WWW_PATH=/usr/share/qdb/www
SHARE_PATH=/usr/share/qdb

# Log
mkdir -p $LOG_PATH
chown $USER:$GROUP $LOG_PATH

# Config
mkdir -p /etc/qdb

# add user for qdb_httpd
qdb_user_add -u qdb_httpd -p $ETC_PATH/users.conf -s $ETC_PATH/qdb_httpd_private.key
chown $USER:$GROUP $ETC_PATH/qdb_httpd_private.key
chmod 0600 $ETC_PATH/qdb_httpd_private.key

# set up with security
[ -e $ETC_PATH/qdb_httpd.conf ] || qdb_httpd --gen-config --daemonize --log-directory=$LOG_PATH --root=$WWW_PATH --cluster-public-key-file=$SHARE_PATH/cluster_public.key --user-credentials-file=$ETC_PATH/qdb_httpd_private.key > $ETC_PATH/qdb_httpd.conf

chown root:root /usr/share/qdb/upstart/qdb_httpd.conf

if ps -p1 | grep -q systemd; then
    # caution: systemd doesn't follow symlink
    cp /usr/share/qdb/systemd/qdb_httpd.service /etc/systemd/system/qdb_httpd.service
    systemctl daemon-reload
    systemctl -q enable qdb_httpd.service
    systemctl start qdb_httpd.service
else
    ln -sf /usr/share/qdb/upstart/qdb_httpd.conf /etc/init/qdb_httpd.conf
    initctl reload-configuration
    initctl start qdb_httpd
fi
