#!/bin/sh

# Allow errors to make sure the package can always be removed
set +e

if ps -p1 | grep -q systemd; then

    if systemctl is-active -q qdb_httpd ; then
        echo "Stopping qdb_httpd..."
        systemctl stop qdb_httpd.service
    fi

else

    if initctl status qdb_httpd | grep -q running; then
        echo "Stopping qdb_httpd..."
        initctl --quiet stop qdb_httpd
    fi

fi