#!/bin/sh

USER="qdb"
GROUP="$USER"
ETC_PATH=/etc/qdb

# Config
mkdir -p $ETC_PATH

openssl req -newkey rsa:4096 -nodes -sha512 -x509 -days 3650 -nodes -out $ETC_PATH/rest-api.cert.pem -keyout $ETC_PATH/rest-api.key.pem -subj "/C=FR/L=Paris/O=Quasardb/CN=Quasardb" >/dev/null 2>&1

if [ ! -f $ETC_PATH/qdb_rest.conf ]; then
    cp $ETC_PATH/qdb_rest.conf.sample $ETC_PATH/qdb_rest.conf
fi

chown -R $USER:$GROUP $ETC_PATH

cp -f /usr/share/qdb/systemd/qdb_api_rest.service /etc/systemd/system/qdb_api_rest.service

systemctl daemon-reload 2>&1 || true
systemctl -q enable qdb_api_rest.service
systemctl run qdb_api_rest.service 2>&1 || true
