#!/bin/sh

set -e

if [ "$1" = "purge" ]
then
 rm -rf /var/lib/qdb
 rm -rf /etc/qdb
 rm -rf /var/run/qdb
 userdel qdb
fi

rm -f /etc/init/qdbd.conf
rm -f /etc/init/qdb_httpd.conf

initctl reload-configuration